[server]
; enter your desired port
port = 3000

[paths]
; enter your desired paths for those 3
media_dir = media
thumbs_dir = thumbnails
convert_dir = converted

[hls]
; cut segment time, below 1.0 is not recommended
segment_time = 5.0
resolution = 854x480